### ISSUE TITLE
Mejorar el README

### ISSUE THREAD

**Issue by cofinoa** [Yemilec/Unix_Git#1]
Hola @Yemilec, 
Con respecto al README.md mejoralo intentado seguir este template:
https://gist.github.com/PurpleBooth/109311bb0361f32d87a2

no necesitas completar todas las secciones. 

Gracias

Antonio

**Comment by sixtohg** [comment]
El README no sigue el template propuesto en el ticket. Le faltan la mayoría de los campos los cuales, con la información incluida actualmente, podrían ser aplicables. Entre otros cambios, yo incluiría la orden con la cual te instalas una working copy del repositorio en local. Hablas de cuatro scripts, y defines cuatro, pero citas tres en la frase. Hay alguna falta gramatical en el texto. Debes separar claramente el comando de ejecución del script, dándole entidad. Sería adecuado, al menos a título ilustrativo, decir cual es ese "orden correspondiente" que usa el script0.sh.
