### ISSUE TITLE
Añadir al .gitignore los archivos .DStore

### ISSUE THREAD

**Issue by cofinoa** [Yemilec/Unix_Git#2]
Añade al .gitignore los arechivos .DStore de OSX. 
Un saludo
Antonio

**Comment by sixtohg** [comment]
Está resuelto en el repositorio pero no en el ticket, ¿hay alguna razón?

**Comment by Yemilec** [comment]
Creo que no sé muy bien a que te refieres con el ticket...

**Comment by sixtohg** [comment]
Hola, me refiero a que, según he visto en el fichero, ya has resuelto este ticket pero no lo has definido como resuelto, si no que sigue abierto. Siempre que resuelvas un issue debes cerrarlo definiéndolo como "solved" o "closed" depende de la aplicación.
