### ISSUE TITLE
Mejorar comentarios

### ISSUE THREAD

**Issue by cofinoa** [Yemilec/Unix_Git#3]
Añade al principio de los scripts un pequeño comentario sobre que es lo que hace el script.

**Comment by sixtohg** [comment]
Cuando hacemos referencia a los comentarios entran en juego diferentes dimensiones. Por ejemplo, debes tratar de que el comentario no tenga una anchura demasiado extensa, debiera poder leerse sin una pantalla de 24 pulgadas. 

Por más que se puedan entender las instrucciones, en shell tienden a agruparse y a enlazarse diferentes instrucciones en una misma línea, de modo que o se incluye un comentario clarificando qué hace en esa línea o resulta difícil de interpretar. Si las instrucciones son muy claras, no es necesario. Si forman un bloque basta con comentar el bloque en lugar de cada línea por separado.

Finalmente, los scripts deben tener comentarios al comienzo que reflejen lo que hace, como se ejecuta, de que depende (si existen dependencias relevantes no estándares) y quien lo ha implementado.
