### ISSUE TITLE
Define la lista de meses como una variable

### ISSUE THREAD

**Issue by cofinoa** [Yemilec/Unix_Git#4]
https://github.com/Yemilec/Unix_Git/blob/a841f7011d69cbd05877c76c9a89578143ec0c53/UnixGitHub.sh#L9

**Comment by sixtohg** [comment]
Aunque hace referencia a una variable en particular, es aplicable a todas las que usas para definir los bucles. Debes definir la variable y luego hacer uso de ella en el bucle, de ese modo si tienes que usarla en más de una ocasión no tienes que replicar gran cantidad de código de forma innecesaria, evitando errores asociados a la redundancia.
